default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: file-manager_development
test:
  <<: *default
  database: file-manager_test
production:
  <<: *default
  database: file-manager_production
  username: file-manager
  password: <%= ENV['FILE-MANAGER_DATABASE_PASSWORD'] %>
